### ISSUE TITLE
Fail to build with libtorrent-rasterbar-dev 1.1.1

### ISSUE THREAD

**Issue by petterreinholdtsen** [johang/vlc-bittorrent#25]
When trying to build the latest git source, it fail on Debian Stretch with vlc 3 backported.  This is the start of errors I get:

```
In file included from data.cpp:25:0:
libtorrent.h:47:39: error: ‘lt’ has not been declared
 libtorrent_add_download(Download *dl, lt::add_torrent_params& atp);
                                       ^~
libtorrent.h:47:61: error: expected ‘,’ or ‘...’ before ‘&’ token
 libtorrent_add_download(Download *dl, lt::add_torrent_params& atp);
                                                             ^
In file included from module.cpp:20:0:
libtorrent.h:47:39: error: ‘lt’ has not been declared
 libtorrent_add_download(Download *dl, lt::add_torrent_params& atp);
                                       ^~
libtorrent.h:47:61: error: expected ‘,’ or ‘...’ before ‘&’ token
 libtorrent_add_download(Download *dl, lt::add_torrent_params& atp);
                                                             ^
In file included from data.cpp:29:0:
download.h:50:16: error: ‘lt’ has not been declared
  process_alert(lt::alert *alert);
                ^~
download.h:50:26: error: expected ‘,’ or ‘...’ before ‘*’ token
  process_alert(lt::alert *alert);
                          ^
[...]
```

Is a newer version of libtorrent required?

**Comment by petterreinholdtsen** [comment]
For the record, it build when using version libtorrent-rasterbar-dev 1.1.11.
